In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
a1 = np.array([1,2,3])

a2 = np.array([[1,2,3],[4,5,6]])

a3 = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],
       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [3]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [4]:
a1.shape 

(3,)

In [5]:
a2.shape

(2, 3)

In [6]:
a3.shape

(3, 3, 3)

In [7]:
a1.size

3

In [8]:
a2.size

6

In [9]:
a3.size

27

In [10]:
a1.dtype

dtype('int32')

In [11]:
a2.dtype

dtype('int32')

In [12]:
a3.dtype

dtype('int32')

In [13]:
a1.itemsize

4

In [14]:
a2.itemsize

4

In [15]:
a2.itemsize

4

In [16]:
a1.data

In [17]:
a3.data

In [18]:
dts = pd.DataFrame(a2)

In [19]:
dts

0  1  2
0  1  2  3
1  4  5  6

In [20]:
dws = np.ones((10, 2))

In [21]:
dws

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
dws1 = np.zeros((7, 2, 4))

In [23]:
dws1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
 np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
dys = np.random.rand(7,2)

In [26]:
dys

array([[0.21608858, 0.53811412],
       [0.62841592, 0.46172451],
       [0.13142237, 0.09036567],
       [0.01083724, 0.51290616],
       [0.1817684 , 0.37441984],
       [0.96556894, 0.82849124],
       [0.96184477, 0.91521915]])

In [27]:
np.random.seed(seed=9999)
dys1 = np.random.randint(10,size=(7,2))

In [28]:
dys

array([[0.21608858, 0.53811412],
       [0.62841592, 0.46172451],
       [0.13142237, 0.09036567],
       [0.01083724, 0.51290616],
       [0.1817684 , 0.37441984],
       [0.96556894, 0.82849124],
       [0.96184477, 0.91521915]])

In [29]:
dys1

array([[6, 1],
       [6, 5],
       [5, 9],
       [6, 8],
       [0, 8],
       [1, 5],
       [3, 1]])

In [30]:
s = np.random.uniform(low=0, high=1, size=(3,5))

In [31]:
s

array([[0.60016319, 0.71124865, 0.31619165, 0.07488889, 0.67401502],
       [0.94746435, 0.22389493, 0.35152287, 0.26615216, 0.4653527 ],
       [0.08001754, 0.72121787, 0.71121665, 0.97670541, 0.1853321 ]])

In [32]:
np.random.seed(seed=42)
dys1 = np.random.randint(10,size=(4,6))

In [33]:
dys1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [34]:
s1 = np.random.randint(10,size=(3,7))

In [35]:
s1

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [36]:
s2 = np.unique(s1)

In [37]:
s2

array([0, 1, 2, 3, 4, 6, 8, 9])

In [38]:
s1[0]

array([8, 0, 9, 2, 6, 3, 8])

In [39]:
s1[0:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [40]:
s1[:2,:2]

array([[8, 0],
       [2, 4]])

In [41]:
w = np.random.randint(10,size=(3,5))

In [42]:
w1 = np.ones((3,5))

In [43]:
w

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [44]:
w1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
w3 = w + w1

In [46]:
w2 = np.ones((5,3))

In [47]:
w2 = np.ones((3,5))

In [48]:
w4 = w3 - w2

In [49]:
w5 = w4*w3

In [50]:
w5

array([[20.,  2., 12., 42., 56.],
       [ 6.,  0., 12.,  2., 56.],
       [12.,  2., 30., 30., 90.]])

In [51]:
w6 = w4**w3

In [52]:
w6

array([[1.0240000e+03, 1.0000000e+00, 8.1000000e+01, 2.7993600e+05,
        5.7648010e+06],
       [8.0000000e+00, 0.0000000e+00, 8.1000000e+01, 1.0000000e+00,
        5.7648010e+06],
       [8.1000000e+01, 1.0000000e+00, 1.5625000e+04, 1.5625000e+04,
        3.4867844e+09]])

In [53]:
w7 = np.square(w5)

In [54]:
w7

array([[4.000e+02, 4.000e+00, 1.440e+02, 1.764e+03, 3.136e+03],
       [3.600e+01, 0.000e+00, 1.440e+02, 4.000e+00, 3.136e+03],
       [1.440e+02, 4.000e+00, 9.000e+02, 9.000e+02, 8.100e+03]])

In [55]:
np.mean(w5)

24.8

In [56]:
np.max(w5)

90.0

In [57]:
np.min(w5)

0.0

In [58]:
np.std(w5)

25.285569006846575

In [59]:
np.var(w5)

639.3600000000001

In [60]:
a = np.reshape(w5, (3, 5, 1))

In [61]:
a


array([[[20.],
        [ 2.],
        [12.],
        [42.],
        [56.]],

       [[ 6.],
        [ 0.],
        [12.],
        [ 2.],
        [56.]],

       [[12.],
        [ 2.],
        [30.],
        [30.],
        [90.]]])

In [62]:
np.transpose(w5)

array([[20.,  6., 12.],
       [ 2.,  0.,  2.],
       [12., 12., 30.],
       [42.,  2., 30.],
       [56., 56., 90.]])